apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fabric-ca-orgx-pvc
  namespace: orgx
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-path
---
apiVersion: v1
kind: Service
metadata:
  name: fabric-ca-orgx
  namespace: orgx
spec:
  selector:
    app: fabric-ca-orgx
  ports:
    - name: https
      port: 7054
      targetPort: 7054
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fabric-ca-orgx
  namespace: orgx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fabric-ca-orgx
  template:
    metadata:
      labels:
        app: fabric-ca-orgx
    spec:
      containers:
      - name: fabric-ca
        image: hyperledger/fabric-ca:1.5.9
        imagePullPolicy: IfNotPresent
        command: ["sh","-c"]
        args:
          - fabric-ca-server start
        ports:
          - containerPort: 7054
        env:
          - name: FABRIC_CA_HOME
            value: /etc/hyperledger/fabric-ca-server
          - name: FABRIC_CA_SERVER_TLS_ENABLED
            value: "true"
          - name: FABRIC_CA_SERVER_TLS_CERTFILE
            value: /etc/hyperledger/fabric-ca-server/tls/cert.pem
          - name: FABRIC_CA_SERVER_TLS_KEYFILE
            value: /etc/hyperledger/fabric-ca-server/tls/key.pem
        volumeMounts:
          - name: data
            mountPath: /etc/hyperledger/fabric-ca-server
          - name: tls
            mountPath: /etc/hyperledger/fabric-ca-server/tls
            readOnly: true
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: fabric-ca-orgx-pvc
        - name: tls
          secret:
            secretName: fabric-ca-orgx-tls

