apiVersion: v1
kind: Pod
metadata:
  name: debug-peer2-tls
  namespace: orgx
spec:
  restartPolicy: Never
  containers:
  - name: debug
    image: alpine
    command: ["sleep","3600"]
    volumeMounts:
    - name: tls
      mountPath: /tls
  volumes:
  - name: tls
    persistentVolumeClaim:
      claimName: peer2-orgx-tls-pvc
