# crea •	fabric-ca-server-config.yaml
#     •	ca-cert.pem
#     •	fabric-ca-server.db

apiVersion: batch/v1
kind: Job
metadata:
  name: fabric-ca-orgdcms-init
  namespace: orgdcms
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: fabric-ca-init
          image: hyperledger/fabric-ca:1.5.9
          command: ["sh","-c"]
          args:
            - |
              set -e
              fabric-ca-server init -b admin:adminpw
          env:
            - name: FABRIC_CA_HOME
              value: /etc/hyperledger/fabric-ca-server
          volumeMounts:
            - name: data
              mountPath: /etc/hyperledger/fabric-ca-server
            
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: fabric-ca-orgdcms-pvc

