apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"fabric-ca","namespace":"orgdcms"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"fabric-ca"}},"template":{"metadata":{"labels":{"app":"fabric-ca"}},"spec":{"containers":[{"args":["sh","-c","fabric-ca-server start -b admin:adminpw --tls.enabled"],"env":[{"name":"FABRIC_CA_HOME","value":"/etc/hyperledger/fabric-ca-server"},{"name":"FABRIC_CA_SERVER_TLS_ENABLED","value":"true"}],"image":"hyperledger/fabric-ca:1.5.13","name":"ca","ports":[{"containerPort":7054}],"volumeMounts":[{"mountPath":"/etc/hyperledger/fabric-ca-server","name":"data"}]}],"volumes":[{"name":"data","persistentVolumeClaim":{"claimName":"fabric-ca-pvc"}}]}}}}
  creationTimestamp: "2026-01-01T20:20:51Z"
  generation: 9
  name: fabric-ca
  namespace: orgdcms
  resourceVersion: "103013"
  uid: 526a9f4d-630e-4255-af89-b73032c93b19
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: fabric-ca
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: fabric-ca
    spec:
      containers:
      - args:
        - sh
        - -c
        - fabric-ca-server start -b admin:adminpw --tls.enabled
        env:
        - name: FABRIC_CA_HOME
          value: /etc/hyperledger/fabric-ca-server
        - name: FABRIC_CA_SERVER_TLS_ENABLED
          value: "true"
        image: hyperledger/fabric-ca:1.5.13
        imagePullPolicy: IfNotPresent
        name: ca
        ports:
        - containerPort: 7054
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/hyperledger/fabric-ca-server
          name: data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: fabric-ca-pvc
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2026-01-01T20:20:51Z"
    lastUpdateTime: "2026-01-04T18:04:02Z"
    message: ReplicaSet "fabric-ca-b9848678" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2026-01-04T18:19:48Z"
    lastUpdateTime: "2026-01-04T18:19:48Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 9
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
