apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"fabric-ca-pvc","namespace":"orgdcms"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"2Gi"}},"storageClassName":"local-path"}}
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
      volume.kubernetes.io/selected-node: beelink-fabric
      volume.kubernetes.io/storage-provisioner: rancher.io/local-path
    creationTimestamp: "2026-01-12T16:11:47Z"
    finalizers:
    - kubernetes.io/pvc-protection
    name: fabric-ca-pvc
    namespace: orgdcms
    resourceVersion: "340757"
    uid: ffe649f7-ba76-4400-9f3f-2df96101ba28
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 2Gi
    storageClassName: local-path
    volumeMode: Filesystem
    volumeName: pvc-ffe649f7-ba76-4400-9f3f-2df96101ba28
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 2Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"fabric-tls-ca-pvc","namespace":"orgdcms"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"2Gi"}},"storageClassName":"local-path"}}
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
      volume.kubernetes.io/selected-node: beelink-fabric
      volume.kubernetes.io/storage-provisioner: rancher.io/local-path
    creationTimestamp: "2026-01-12T16:03:55Z"
    finalizers:
    - kubernetes.io/pvc-protection
    name: fabric-tls-ca-pvc
    namespace: orgdcms
    resourceVersion: "340459"
    uid: d5ab0e34-0ead-4192-97a4-be640bc76792
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 2Gi
    storageClassName: local-path
    volumeMode: Filesystem
    volumeName: pvc-d5ab0e34-0ead-4192-97a4-be640bc76792
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 2Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"fabric-ca-pvc","namespace":"orgx"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"2Gi"}},"storageClassName":"local-path"}}
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
      volume.kubernetes.io/selected-node: beelink-fabric
      volume.kubernetes.io/storage-provisioner: rancher.io/local-path
    creationTimestamp: "2026-01-12T16:03:55Z"
    finalizers:
    - kubernetes.io/pvc-protection
    name: fabric-ca-pvc
    namespace: orgx
    resourceVersion: "341089"
    uid: e38b1a81-239d-45b8-988e-98ba2e70de74
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 2Gi
    storageClassName: local-path
    volumeMode: Filesystem
    volumeName: pvc-e38b1a81-239d-45b8-988e-98ba2e70de74
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 2Gi
    phase: Bound
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"fabric-tls-ca-pvc","namespace":"orgx"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"2Gi"}},"storageClassName":"local-path"}}
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
      volume.kubernetes.io/selected-node: beelink-fabric
      volume.kubernetes.io/storage-provisioner: rancher.io/local-path
    creationTimestamp: "2026-01-12T16:03:55Z"
    finalizers:
    - kubernetes.io/pvc-protection
    name: fabric-tls-ca-pvc
    namespace: orgx
    resourceVersion: "341096"
    uid: 6b701696-a1be-4ce9-ae38-0bca5ee31a8e
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 2Gi
    storageClassName: local-path
    volumeMode: Filesystem
    volumeName: pvc-6b701696-a1be-4ce9-ae38-0bca5ee31a8e
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 2Gi
    phase: Bound
kind: List
metadata:
  resourceVersion: ""
