#pod di accesso in scrittura al PVC
apiVersion: batch/v1
kind: Job
metadata:
  name: tls-fix-peer2
  namespace: orgx
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: fix
        image: busybox
        command:
          - sh
          - -c
          - |
            mkdir -p /mnt/tls/trusted
            cp /src/peer1-tls-ca.crt /mnt/tls/trusted/
            ls -l /mnt/tls/trusted
            echo DONE
        volumeMounts:
        - name: tls
          mountPath: /mnt/tls
        - name: src
          mountPath: /src
      volumes:
      - name: tls
        persistentVolumeClaim:
          claimName: peer2-orgx-tls-pvc
      - name: src
        hostPath:
          path: /home/asantopadre
          type: Directory
