#inserisce nel bundle delle tls ca tutte  e tre le tls root
apiVersion: batch/v1
kind: Job
metadata:
  name: bundle-peer1
  namespace: orgdcms
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: bundle
        image: busybox
        command:
          - sh
          - -c
          - |
            echo "Rebuilding TLS bundle..."
            cat /tls/ca.crt \
                /tls/trusted/peer2-tls-ca.crt \
                /common/tls-ca-cert.pem \
                > /tls/ca-bundle.crt

            echo "=== /tls directory ==="
            ls -l /tls

            echo "=== certificate count ==="
            grep -c "BEGIN CERTIFICATE" /tls/ca-bundle.crt

        volumeMounts:
        - name: tls
          mountPath: /tls

        - name: common-tls-ca
          mountPath: /common
          readOnly: true

      volumes:
      - name: tls
        persistentVolumeClaim:
          claimName: peer1-orgdcms-tls-pvc

      - name: common-tls-ca
        hostPath:
          path: /home/asantopadre/fabric-deploy/tls-ca
          type: Directory
