apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"creationTimestamp":"2026-01-05T13:04:42Z","name":"orderer1","namespace":"orgdcms","resourceVersion":"131535","uid":"36d7ecbb-8dac-454c-8364-08d89e527e4d"},"spec":{"clusterIP":"10.43.3.32","clusterIPs":["10.43.3.32"],"internalTrafficPolicy":"Cluster","ipFamilies":["IPv4"],"ipFamilyPolicy":"SingleStack","ports":[{"name":"grpc","port":7050,"protocol":"TCP","targetPort":7050},{"name":"admin","port":7053,"protocol":"TCP","targetPort":7053}],"selector":{"app":"orderer1"},"sessionAffinity":"None","type":"ClusterIP"},"status":{"loadBalancer":{}}}
  creationTimestamp: "2026-01-05T13:04:42Z"
  name: orderer1
  namespace: orgdcms
  resourceVersion: "160732"
  uid: 36d7ecbb-8dac-454c-8364-08d89e527e4d
spec:
  clusterIP: 10.43.3.32
  clusterIPs:
  - 10.43.3.32
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: grpc
    port: 7050
    protocol: TCP
    targetPort: 7050
  - name: admin
    port: 7053
    protocol: TCP
    targetPort: 7053
  selector:
    app: orderer1
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
