apiVersion: v1
kind: Service
metadata:
  name: orderer3
  namespace: orgx
spec:
  selector:
    app: orderer3
  ports:
  - name: grpc
    port: 7050
    targetPort: 7050
  - name: admin
    port: 7053
    targetPort: 7053
