apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"peer2","namespace":"orgx"},"spec":{"ports":[{"name":"grpc","port":7051,"targetPort":7051},{"name":"chaincode","port":7052,"targetPort":7052}],"selector":{"app":"peer2"}}}
  creationTimestamp: "2026-02-20T23:32:00Z"
  name: peer2
  namespace: orgx
  resourceVersion: "1417539"
  uid: 485035ef-3612-4e83-9d26-487473773b92
spec:
  clusterIP: 10.43.225.204
  clusterIPs:
  - 10.43.225.204
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: grpc
    port: 7051
    protocol: TCP
    targetPort: 7051
  - name: chaincode
    port: 7052
    protocol: TCP
    targetPort: 7052
  selector:
    app: peer2
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
