apiVersion: v1
kind: Pod
metadata:
  name: populate-peer2-pvc
  namespace: orgx
spec:
  restartPolicy: Never
  containers:
    - name: populate
      image: busybox:1.36
      command:
        - sh
        - -lc
        - |
          set -e
          rm -rf /msp/* /tls/*
          cp -R /src/msp/* /msp/
          cp /src/tls/ca.crt /tls/ca.crt
          cp /src/tls/server.crt /tls/server.crt
          cp /src/tls/server.key /tls/server.key
          echo "PVC populated"
          sleep 5
      volumeMounts:
        - name: src
          mountPath: /src
          readOnly: true
        - name: msp
          mountPath: /msp
        - name: tls
          mountPath: /tls
  volumes:
    - name: src
      hostPath:
        path: /home/asantopadre/fabric-deploy/orgx/peers/peer2
        type: Directory
    - name: msp
      persistentVolumeClaim:
        claimName: peer2-orgx-msp-pvc
    - name: tls
      persistentVolumeClaim:
        claimName: peer2-orgx-tls-pvc
