# k8s/orgdcms/pvc/orderer2-msp-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orderer2-msp-pvc
  namespace: orgdcms
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
