apiVersion: batch/v1
kind: Job
metadata:
  name: enroll-osnadmin-tls
  namespace: orgdcms
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: enroll
        image: hyperledger/fabric-ca:1.5
        env:
        - name: FABRIC_CA_CLIENT_HOME
          value: /osnadmin
        - name: FABRIC_CA_CLIENT_TLS_CERTFILES
          value: /tlsca/tls-cert.pem
        command:
        - /bin/sh
        - -c
        - |
          set -e
          echo "== Enroll osnadmin TLS =="
          fabric-ca-client enroll \
            -u https://osnadmin:osnadminpw@fabric-tls-ca.orgdcms.svc.cluster.local:7052 \
            --caname tlsca-orgdcms \
            --enrollment.profile tls \
            --mspdir /osnadmin/msp
          echo "== DONE =="
        volumeMounts:
        - name: osnadmin-tls
          mountPath: /osnadmin
        - name: tlsca
          mountPath: /tlsca
          readOnly: true

      volumes:
      - name: osnadmin-tls
        persistentVolumeClaim:
          claimName: osnadmin-tls-pvc
      - name: tlsca
        persistentVolumeClaim:
          claimName: fabric-tls-ca-pvc
