apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fabric-ca-pvc
  namespace: orgdcms
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-path
