apiVersion: apps/v1
kind: Deployment
metadata:
  name: fabric-tls-ca
  namespace: orgdcms
spec:
  replicas: 1
  selector:
    matchLabels: { app: fabric-tls-ca }
  template:
    metadata:
      labels: { app: fabric-tls-ca }
    spec:
      containers:
      - name: fabric-tls-ca
        image: hyperledger/fabric-ca:1.5
        env:
        - name: FABRIC_CA_HOME
          value: /etc/hyperledger/fabric-ca-server
        - name: FABRIC_CA_SERVER_CA_NAME
          value: tlsca-orgdcms
        - name: FABRIC_CA_SERVER_PORT
          value: "7052"
        - name: FABRIC_CA_SERVER_TLS_ENABLED
          value: "true"
        - name: FABRIC_CA_SERVER_TLS_CERTFILE
          value: /etc/hyperledger/fabric-ca-server/tls-ca-cert.pem
        - name: FABRIC_CA_SERVER_TLS_KEYFILE
          value: /etc/hyperledger/fabric-ca-server/tls-ca-key.pem
        ports:
        - containerPort: 7052
        volumeMounts:
        - name: tls-ca-data
          mountPath: /etc/hyperledger/fabric-ca-server
      volumes:
      - name: tls-ca-data
        persistentVolumeClaim:
          claimName: fabric-tls-ca-pvc
