# k8s/orgdcms/ca/ca-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: fabric-ca
  namespace: orgdcms
spec:
  type: ClusterIP
  selector:
    app: fabric-ca
  ports:
  - port: 7054
    targetPort: 7054
