apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "2"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"fabric-ca","namespace":"orgx"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"fabric-ca"}},"template":{"metadata":{"labels":{"app":"fabric-ca"}},"spec":{"containers":[{"env":[{"name":"FABRIC_CA_HOME","value":"/etc/hyperledger/fabric-ca-server"},{"name":"FABRIC_CA_SERVER_CA_NAME","value":"ca-orgx"},{"name":"FABRIC_CA_SERVER_PORT","value":"7054"},{"name":"FABRIC_CA_SERVER_TLS_ENABLED","value":"true"}],"image":"hyperledger/fabric-ca:1.5","name":"fabric-ca","ports":[{"containerPort":7054}],"volumeMounts":[{"mountPath":"/etc/hyperledger/fabric-ca-server","name":"ca-data"}]}],"volumes":[{"name":"ca-data","persistentVolumeClaim":{"claimName":"fabric-ca-pvc"}}]}}}}
    creationTimestamp: "2026-01-12T16:17:12Z"
    generation: 2
    name: fabric-ca
    namespace: orgx
    resourceVersion: "341195"
    uid: 4a14f274-c255-407a-bb8e-3e4149682468
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: fabric-ca
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: fabric-ca
      spec:
        containers:
        - env:
          - name: FABRIC_CA_HOME
            value: /etc/hyperledger/fabric-ca-server
          - name: FABRIC_CA_SERVER_CA_NAME
            value: ca-orgx
          - name: FABRIC_CA_SERVER_PORT
            value: "7054"
          - name: FABRIC_CA_SERVER_TLS_ENABLED
            value: "true"
          image: hyperledger/fabric-ca:1.5
          imagePullPolicy: IfNotPresent
          name: fabric-ca
          ports:
          - containerPort: 7054
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /etc/hyperledger/fabric-ca-server
            name: ca-data
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: ca-data
          persistentVolumeClaim:
            claimName: fabric-ca-pvc
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2026-01-12T16:17:16Z"
      lastUpdateTime: "2026-01-12T16:17:16Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2026-01-12T16:17:12Z"
      lastUpdateTime: "2026-01-12T16:18:05Z"
      message: ReplicaSet "fabric-ca-775cbf87d6" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 2
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "2"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"fabric-tls-ca","namespace":"orgx"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"fabric-tls-ca"}},"template":{"metadata":{"labels":{"app":"fabric-tls-ca"}},"spec":{"containers":[{"env":[{"name":"FABRIC_CA_HOME","value":"/etc/hyperledger/fabric-ca-server"},{"name":"FABRIC_CA_SERVER_CA_NAME","value":"tlsca-orgx"},{"name":"FABRIC_CA_SERVER_PORT","value":"7052"},{"name":"FABRIC_CA_SERVER_TLS_ENABLED","value":"true"}],"image":"hyperledger/fabric-ca:1.5","name":"fabric-tls-ca","ports":[{"containerPort":7052}],"volumeMounts":[{"mountPath":"/etc/hyperledger/fabric-ca-server","name":"tls-ca-data"}]}],"volumes":[{"name":"tls-ca-data","persistentVolumeClaim":{"claimName":"fabric-tls-ca-pvc"}}]}}}}
    creationTimestamp: "2026-01-12T16:17:12Z"
    generation: 2
    name: fabric-tls-ca
    namespace: orgx
    resourceVersion: "341191"
    uid: b53ef409-cae5-47ec-b81d-61a984e92ad8
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: fabric-tls-ca
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: fabric-tls-ca
      spec:
        containers:
        - env:
          - name: FABRIC_CA_HOME
            value: /etc/hyperledger/fabric-ca-server
          - name: FABRIC_CA_SERVER_CA_NAME
            value: tlsca-orgx
          - name: FABRIC_CA_SERVER_PORT
            value: "7052"
          - name: FABRIC_CA_SERVER_TLS_ENABLED
            value: "true"
          image: hyperledger/fabric-ca:1.5
          imagePullPolicy: IfNotPresent
          name: fabric-tls-ca
          ports:
          - containerPort: 7052
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /etc/hyperledger/fabric-ca-server
            name: tls-ca-data
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: tls-ca-data
          persistentVolumeClaim:
            claimName: fabric-tls-ca-pvc
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2026-01-12T16:17:16Z"
      lastUpdateTime: "2026-01-12T16:17:16Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2026-01-12T16:17:12Z"
      lastUpdateTime: "2026-01-12T16:18:05Z"
      message: ReplicaSet "fabric-tls-ca-687cdc98fc" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 2
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "5"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"9"},"creationTimestamp":"2026-01-12T17:42:15Z","generation":9,"name":"orderer3","namespace":"orgx","resourceVersion":"345775","uid":"6e653c3a-3ac4-4b7e-ac44-e8619777801c"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"orderer3"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"annotations":{"kubectl.kubernetes.io/restartedAt":"2026-01-12T19:14:36Z"},"creationTimestamp":null,"labels":{"app":"orderer3"}},"spec":{"containers":[{"env":[{"name":"ORDERER_GENERAL_LISTENADDRESS","value":"0.0.0.0"},{"name":"ORDERER_GENERAL_LISTENPORT","value":"7050"},{"name":"ORDERER_GENERAL_LOCALMSPID","value":"OrgDCMSOrdererMSP"},{"name":"ORDERER_GENERAL_LOCALMSPDIR","value":"/var/hyperledger/orderer/msp"},{"name":"ORDERER_GENERAL_TLS_ENABLED","value":"true"},{"name":"ORDERER_GENERAL_TLS_PRIVATEKEY","value":"/var/hyperledger/orderer/tls/keystore/key.pem"},{"name":"ORDERER_GENERAL_TLS_CERTIFICATE","value":"/var/hyperledger/orderer/tls/signcerts/cert.pem"},{"name":"ORDERER_GENERAL_TLS_ROOTCAS","value":"/var/hyperledger/orderer/tls/tlscacerts/tls-localhost-7052-tlsca-orgx.pem"},{"name":"ORDERER_ADMIN_LISTENADDRESS","value":"0.0.0.0:7053"},{"name":"ORDERER_ADMIN_TLS_ENABLED","value":"true"},{"name":"ORDERER_ADMIN_TLS_CERTIFICATE","value":"/var/hyperledger/orderer/tls/signcerts/cert.pem"},{"name":"ORDERER_ADMIN_TLS_PRIVATEKEY","value":"/var/hyperledger/orderer/tls/keystore/key.pem"},{"name":"ORDERER_GENERAL_BOOTSTRAPMETHOD","value":"none"}],"image":"hyperledger/fabric-orderer:2.4","imagePullPolicy":"IfNotPresent","name":"orderer","resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/var/hyperledger/orderer/msp","name":"msp"},{"mountPath":"/var/hyperledger/orderer/tls","name":"tls"}]}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30,"volumes":[{"hostPath":{"path":"/home/asantopadre/runtime/orgx/orderer3/msp","type":""},"name":"msp"},{"hostPath":{"path":"/home/asantopadre/runtime/orgx/orderer3/tls","type":""},"name":"tls"}]}}},"status":{"availableReplicas":1,"conditions":[{"lastTransitionTime":"2026-01-12T19:14:05Z","lastUpdateTime":"2026-01-12T19:14:05Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"},{"lastTransitionTime":"2026-01-12T19:14:04Z","lastUpdateTime":"2026-01-12T19:14:37Z","message":"ReplicaSet \"orderer3-5696dcb8bc\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"}],"observedGeneration":9,"readyReplicas":1,"replicas":1,"updatedReplicas":1}}
    creationTimestamp: "2026-01-13T06:34:31Z"
    generation: 7
    name: orderer3
    namespace: orgx
    resourceVersion: "380842"
    uid: ecadd1e5-2393-4547-ac2a-78317456a9e8
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: orderer3
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        annotations:
          kubectl.kubernetes.io/restartedAt: "2026-01-14T00:25:39Z"
        creationTimestamp: null
        labels:
          app: orderer3
      spec:
        containers:
        - env:
          - name: ORDERER_GENERAL_LISTENADDRESS
            value: 0.0.0.0
          - name: ORDERER_GENERAL_LISTENPORT
            value: "7050"
          - name: ORDERER_GENERAL_LOCALMSPID
            value: OrgDCMSOrdererMSP
          - name: ORDERER_GENERAL_LOCALMSPDIR
            value: /var/hyperledger/orderer/msp
          - name: ORDERER_GENERAL_TLS_ENABLED
            value: "true"
          - name: ORDERER_GENERAL_TLS_PRIVATEKEY
            value: /var/hyperledger/orderer/tls/keystore/key.pem
          - name: ORDERER_GENERAL_TLS_CERTIFICATE
            value: /var/hyperledger/orderer/tls/signcerts/cert.pem
          - name: ORDERER_GENERAL_TLS_ROOTCAS
            value: /var/hyperledger/orderer/tls/tlscacerts/tls-localhost-7052-tlsca-orgx.pem
          - name: ORDERER_ADMIN_LISTENADDRESS
            value: 0.0.0.0:7053
          - name: ORDERER_ADMIN_TLS_ENABLED
            value: "true"
          - name: ORDERER_ADMIN_TLS_CERTIFICATE
            value: /var/hyperledger/orderer/tls/signcerts/cert.pem
          - name: ORDERER_ADMIN_TLS_PRIVATEKEY
            value: /var/hyperledger/orderer/tls/keystore/key.pem
          - name: ORDERER_GENERAL_BOOTSTRAPMETHOD
            value: none
          - name: ORDERER_CHANNELPARTICIPATION_ENABLED
            value: "true"
          - name: ORDERER_ADMIN_TLS_CLIENTAUTHREQUIRED
            value: "true"
          - name: ORDERER_ADMIN_TLS_CLIENTROOTCAS
            value: /var/hyperledger/orderer/tls/tlscacerts/tls-localhost-7052-tlsca-orgx.pem
          image: hyperledger/fabric-orderer:2.4
          imagePullPolicy: IfNotPresent
          name: orderer
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /var/hyperledger/orderer/msp
            name: msp
          - mountPath: /var/hyperledger/orderer/tls
            name: tls
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - hostPath:
            path: /home/asantopadre/runtime/orgx/orderer3/msp
            type: ""
          name: msp
        - hostPath:
            path: /home/asantopadre/runtime/orgx/orderer3/tls
            type: ""
          name: tls
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2026-01-13T06:34:31Z"
      lastUpdateTime: "2026-01-14T00:25:39Z"
      message: ReplicaSet "orderer3-57d5746fc9" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    - lastTransitionTime: "2026-01-14T00:32:51Z"
      lastUpdateTime: "2026-01-14T00:32:51Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    observedGeneration: 7
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
kind: List
metadata:
  resourceVersion: ""
