apiVersion: batch/v1
kind: Job
metadata:
  name: enroll-orderer1-tls
  namespace: orgdcms
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: enroll
        image: hyperledger/fabric-ca:1.5
        command: ["sh", "-c"]
        args:
          - |
            set -e
            fabric-ca-client enroll \
              -u https://orderer1:ordererpw@fabric-tls-ca.orgdcms:7052 \
              --enrollment.profile tls \
              --csr.cn orderer1 \
              --csr.hosts orderer1 \
              --csr.hosts orderer1.orgdcms \
              --csr.hosts orderer1.orgdcms.svc \
              --csr.hosts orderer1.orgdcms.svc.cluster.local \
              --csr.hosts orderer1-hl \
              --csr.hosts orderer1-hl.orgdcms \
              --csr.hosts orderer1-hl.orgdcms.svc \
              --csr.hosts orderer1-hl.orgdcms.svc.cluster.local \
              -M /var/hyperledger/orderer/tls
            # RINOMINA OBBLIGATORIA (TLS layout atteso dall'orderer)
              cp /var/hyperledger/orderer/tls/signcerts/cert.pem \
                 /var/hyperledger/orderer/tls/server.crt

              cp /var/hyperledger/orderer/tls/keystore/*_sk \
                 /var/hyperledger/orderer/tls/server.key

              cp /var/hyperledger/orderer/tls/tlscacerts/*.pem \
                 /var/hyperledger/orderer/tls/ca.crt
        env:
        - name: FABRIC_CA_CLIENT_HOME
          value: /tmp/fabric-ca-client
        - name: FABRIC_CA_CLIENT_TLS_CERTFILES
          value: /etc/hyperledger/fabric-ca-server/tls-cert.pem
        volumeMounts:
            - name: orderer-tls
              mountPath: /var/hyperledger/orderer/tls
            - name: tlsca
              mountPath: /etc/hyperledger/fabric-ca-server
              readOnly: true
      volumes:
        - name: orderer-tls
          persistentVolumeClaim:
            claimName: orderer1-tls-pvc
        - name: tlsca
          persistentVolumeClaim:
            claimName: fabric-tls-ca-pvc

