apiVersion: batch/v1
kind: Job
metadata: { name: enroll-orderer2-tls, namespace: orgdcms }
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: enroll
        image: hyperledger/fabric-ca:1.5
        env:
        - {name: FABRIC_CA_CLIENT_HOME, value: /tmp/fabric-ca-client}
        - {name: FABRIC_CA_CLIENT_TLS_CERTFILES, value: /etc/hyperledger/fabric-ca-server/tls-cert.pem}
        command: ["sh","-c"]
        args:
        - |
          set -e
          fabric-ca-client enroll \
            -u https://orderer2:ordererpw@fabric-tls-ca.orgdcms:7052 \
            --enrollment.profile tls \
            --csr.cn orderer2 \
            --csr.hosts orderer2 \
            --csr.hosts orderer2-hl \
            --csr.hosts orderer2.orgdcms.svc.cluster.local \
            --csr.hosts orderer2-hl.orgdcms.svc.cluster.local \
            -M /var/hyperledger/orderer/tls
          cp /var/hyperledger/orderer/tls/signcerts/cert.pem /var/hyperledger/orderer/tls/server.crt
          cp /var/hyperledger/orderer/tls/keystore/*_sk        /var/hyperledger/orderer/tls/server.key
          cp /var/hyperledger/orderer/tls/tlscacerts/*.pem     /var/hyperledger/orderer/tls/ca.crt
        volumeMounts:
        - {name: tls, mountPath: /var/hyperledger/orderer/tls}
        - {name: tlsca, mountPath: /etc/hyperledger/fabric-ca-server, readOnly: true}
      volumes:
      - name: tls
        persistentVolumeClaim: { claimName: orderer2-tls-pvc }
      - name: tlsca
        secret: { secretName: tlsca-root }
