apiVersion: v1
kind: Pod
metadata:
  name: inspect-orderer2-pvc
  namespace: orgdcms
spec:
  restartPolicy: Never
  containers:
  - name: inspect
    image: busybox
    command: ["sh", "-c", "ls /msp/signcerts && ls /tls/signcerts"]
    volumeMounts:
    - name: msp
      mountPath: /msp
    - name: tls
      mountPath: /tls
  volumes:
  - name: msp
    persistentVolumeClaim:
      claimName: orderer2-msp-pvc
  - name: tls
    persistentVolumeClaim:
      claimName: orderer2-tls-pvc
