# k8s/orgx/tlsca/tlsca-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: fabric-tls-ca
  namespace: orgx
spec:
  type: ClusterIP
  selector:
    app: fabric-tls-ca
  ports:
  - port: 7052
    targetPort: 7052
