# job di bind dei PVC di orderer3
apiVersion: batch/v1
kind: Job
metadata:
  name: bind-orderer3-pvc
  namespace: orgx
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: hold
          image: busybox
          command: ["sh", "-c", "sleep 300"]
          volumeMounts:
            - name: ledger
              mountPath: /var/hyperledger/orderer
            - name: msp
              mountPath: /var/hyperledger/orderer/msp
            - name: tls
              mountPath: /var/hyperledger/orderer/tls
      volumes:
        - name: ledger
          persistentVolumeClaim:
            claimName: orderer3-ledger-pvc
        - name: msp
          persistentVolumeClaim:
            claimName: orderer3-msp-pvc
        - name: tls
          persistentVolumeClaim:
            claimName: orderer3-tls-pvc
